"""
Phase 2 (contacts) loader: turn data/contacts.csv into idempotent upsert SQL.
Generates data/import_contacts.sql.

- customer_id is resolved by matched_customer name via subquery (NULL when blank).
- studio/subdivision are intentionally NOT stored (left blank); role keeps the
  sheet's role text only.
- IDs are deterministic name slugs (suffixed on collision).
"""

import csv
import re

CSV_PATH = "data/contacts.csv"
SQL_PATH = "data/import_contacts.sql"


def slug(s):
    s = (s or "").strip().lower()
    s = re.sub(r"[^a-z0-9]+", "-", s)
    return s.strip("-")


def q(s):
    return "'" + str(s).replace("'", "''") + "'"


def main():
    with open(CSV_PATH, newline="", encoding="utf-8-sig") as f:
        rows = [r for r in csv.DictReader(f) if (r.get("name") or "").strip()]

    seen = {}
    lines = ["-- Generated by tools/import/load_contacts.py (Phase 2: customer contacts)", "BEGIN;", ""]
    linked = 0
    for r in rows:
        name = r["name"].strip()
        role = (r.get("role") or "").strip()
        matched = (r.get("matched_customer") or "").strip()

        cid = slug(name)
        seen[cid] = seen.get(cid, 0) + 1
        if seen[cid] > 1:
            cid = f"{cid}-{seen[cid]}"

        if matched:
            customer_expr = f"(SELECT id FROM customers WHERE name = {q(matched)})"
            linked += 1
        else:
            customer_expr = "NULL"

        lines.append(
            f"INSERT INTO contacts (id, name, email, slack, role, customer_id) VALUES "
            f"({q(cid)}, {q(name)}, '', '', {q(role)}, {customer_expr}) "
            f"ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, role=EXCLUDED.role, "
            f"customer_id=EXCLUDED.customer_id, updated_at=now();"
        )

    lines += ["", "COMMIT;"]
    with open(SQL_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Wrote {SQL_PATH}: {len(rows)} contacts ({linked} linked to a customer, {len(rows) - linked} unlinked)")


if __name__ == "__main__":
    main()
