"""
Phase 1 loader: turn data/hierarchy.csv into idempotent upsert SQL.

Generates data/import_hierarchy.sql which:
  - seeds the standard app_status reference rows
  - upserts subdivisions, studios, and customers (ON CONFLICT DO UPDATE)

IDs are deterministic slugs so re-running the import is idempotent.
"""

import csv
import re

CSV_PATH = "data/hierarchy.csv"
SQL_PATH = "data/import_hierarchy.sql"

APP_STATUSES = [
    ("prototype", "Prototype", "badge-prototype", 0),
    ("pre-production", "Pre-Production", "badge-preprod", 1),
    ("production", "Production", "badge-prod", 2),
    ("soft-launch", "Soft Launch", "badge-proto", 3),
    ("live-worldwide", "Live Worldwide", "badge-live", 4),
    ("sunsetting", "Sunsetting", "badge-sunsetting", 5),
    ("sunset", "Sunset", "badge-sunset", 6),
]


def slug(s):
    s = (s or "").strip().lower()
    s = re.sub(r"[^a-z0-9]+", "-", s)
    return s.strip("-")


def q(s):
    return "'" + str(s).replace("'", "''") + "'"


def main():
    with open(CSV_PATH, newline="", encoding="utf-8-sig") as f:
        rows = [r for r in csv.DictReader(f) if (r.get("customer") or "").strip()]

    subdivisions = {}  # name -> id
    studios = {}       # (sub_name, studio_name) -> (id, sub_id, studio_name)
    customers = []

    for r in rows:
        cust = r["customer"].strip()
        sub = r["subdivision"].strip()
        studio = r["studio"].strip()
        status = (r.get("app_status") or "production").strip() or "production"
        slack = (r.get("slack_channel") or "").strip()

        sub_id = "sub-" + slug(sub)
        subdivisions[sub] = sub_id

        studio_id = "st-" + slug(sub) + "-" + slug(studio)
        studios[(sub, studio)] = (studio_id, sub_id, studio)

        customers.append({
            "id": slug(cust),
            "name": cust,
            "studio_id": studio_id,
            "app_status": status,
            "slack": slack,
        })

    lines = []
    lines.append("-- Generated by tools/import/load_hierarchy.py (Phase 1: hierarchy + customers)")
    lines.append("BEGIN;")
    lines.append("")
    lines.append("-- Reference: app statuses")
    for key, label, badge, pos in APP_STATUSES:
        lines.append(
            f"INSERT INTO app_statuses (key, label, badge, position) VALUES "
            f"({q(key)}, {q(label)}, {q(badge)}, {pos}) "
            f"ON CONFLICT (key) DO UPDATE SET label=EXCLUDED.label, badge=EXCLUDED.badge, position=EXCLUDED.position;"
        )
    lines.append("")
    lines.append("-- Subdivisions")
    for name, sid in sorted(subdivisions.items(), key=lambda kv: kv[1]):
        lines.append(
            f"INSERT INTO subdivisions (id, name) VALUES ({q(sid)}, {q(name)}) "
            f"ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name;"
        )
    lines.append("")
    lines.append("-- Studios")
    for (sub_name, studio_name), (sid, sub_id, _) in sorted(studios.items(), key=lambda kv: kv[1][0]):
        lines.append(
            f"INSERT INTO studios (id, name, subdivision_id) VALUES ({q(sid)}, {q(studio_name)}, {q(sub_id)}) "
            f"ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, subdivision_id=EXCLUDED.subdivision_id;"
        )
    lines.append("")
    lines.append("-- Customers")
    for c in customers:
        lines.append(
            f"INSERT INTO customers (id, name, studio_id, app_status, slack_channel) VALUES "
            f"({q(c['id'])}, {q(c['name'])}, {q(c['studio_id'])}, {q(c['app_status'])}, {q(c['slack'])}) "
            f"ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, studio_id=EXCLUDED.studio_id, "
            f"app_status=EXCLUDED.app_status, slack_channel=EXCLUDED.slack_channel, updated_at=now();"
        )
    lines.append("")
    lines.append("COMMIT;")

    with open(SQL_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Wrote {SQL_PATH}")
    print(f"  {len(subdivisions)} subdivisions, {len(studios)} studios, {len(customers)} customers")


if __name__ == "__main__":
    main()
