"""
Phase 2a loader: turn data/pods.csv + data/people.csv into idempotent upsert SQL.
Generates data/import_people.sql (pods, then engineers). IDs are deterministic slugs.
"""

import csv
import re

POD_ID = lambda name: "pod-" + slug(name)
ENG_ID = lambda name: slug(name)
SQL_PATH = "data/import_people.sql"


def slug(s):
    s = (s or "").strip().lower()
    s = re.sub(r"[^a-z0-9]+", "-", s)
    return s.strip("-")


def q(s):
    return "'" + str(s).replace("'", "''") + "'"


def read_csv(path):
    with open(path, newline="", encoding="utf-8-sig") as f:
        return list(csv.DictReader(f))


def main():
    pods = read_csv("data/pods.csv")
    people = read_csv("data/people.csv")

    lines = ["-- Generated by tools/import/load_people.py (Phase 2a: MGT people + pods)", "BEGIN;", ""]

    lines.append("-- Pods")
    for p in pods:
        name = p["pod"].strip()
        if not name:
            continue
        lines.append(
            f"INSERT INTO pods (id, name) VALUES ({q(POD_ID(name))}, {q(name)}) "
            f"ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name;"
        )

    lines.append("")
    lines.append("-- Engineers (MGT people)")
    for r in people:
        name = r["name"].strip()
        if not name:
            continue
        pod = r.get("pod", "").strip()
        pod_id = POD_ID(pod) if pod else None
        pod_val = q(pod_id) if pod_id else "NULL"
        lines.append(
            f"INSERT INTO engineers (id, name, initials, pod_id) VALUES "
            f"({q(ENG_ID(name))}, {q(name)}, {q(r.get('initials', '').strip())}, {pod_val}) "
            f"ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, initials=EXCLUDED.initials, pod_id=EXCLUDED.pod_id;"
        )

    lines.append("")
    lines.append("COMMIT;")

    with open(SQL_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Wrote {SQL_PATH}: {len(pods)} pods, {len(people)} engineers")


if __name__ == "__main__":
    main()
