"""
Phase 2B loader: build idempotent SQL from
  data/new_contacts.csv  -> contacts (external attendees discovered in logs)
  data/interactions.csv  -> interactions (+ mgt / external attendee links)
  data/team_notes.csv    -> team_notes

Writes data/import_interactions.sql. IDs are deterministic slugs so re-runs upsert.
Attendees are linked by name subquery (robust to id scheme); missing names no-op.
"""

import csv
import re

SQL_PATH = "data/import_interactions.sql"


def slug(s):
    s = (s or "").strip().lower()
    s = re.sub(r"[^a-z0-9]+", "-", s)
    return s.strip("-")


def q(s):
    return "'" + str(s).replace("'", "''") + "'"


def read(path):
    with open(path, newline="", encoding="utf-8-sig") as f:
        return list(csv.DictReader(f))


def first_name_map():
    """unique-first-name -> full engineer name (for resolving 'Tonya'/'Kyle' authors)."""
    counts, full = {}, {}
    for r in read("data/people.csv"):
        n = r["name"].strip()
        if not n:
            continue
        fn = n.split()[0].lower()
        counts[fn] = counts.get(fn, 0) + 1
        full[fn] = n
    return {fn: full[fn] for fn, c in counts.items() if c == 1}


def uid(base, seen):
    base = base[:60].strip("-") or "x"
    seen[base] = seen.get(base, 0) + 1
    return base if seen[base] == 1 else f"{base}-{seen[base]}"


def combine(context, body):
    context, body = context.strip(), body.strip()
    if context and body:
        return context + "\n\n" + body
    return context or body


def main():
    fmap = first_name_map()
    lines = ["-- Generated by tools/import/load_interactions.py (Phase 2B)", "BEGIN;", ""]

    # --- New external contacts discovered in interaction logs ---
    lines.append("-- New external contacts (from interaction attendee/giver cells)")
    for r in read("data/new_contacts.csv"):
        name = r["name"].strip()
        if not name:
            continue
        cid = "ext-" + slug(name)
        email = (r.get("email") or "").strip()
        cust = (r.get("customer") or "").strip()
        cust_expr = f"(SELECT id FROM customers WHERE name = {q(cust)})" if cust else "NULL"
        lines.append(
            f"INSERT INTO contacts (id, name, email, slack, role, customer_id) VALUES "
            f"({q(cid)}, {q(name)}, {q(email)}, '', '', {cust_expr}) "
            f"ON CONFLICT (id) DO UPDATE SET "
            f"email = CASE WHEN EXCLUDED.email <> '' THEN EXCLUDED.email ELSE contacts.email END, "
            f"customer_id = COALESCE(contacts.customer_id, EXCLUDED.customer_id), updated_at = now();"
        )
    lines.append("")

    # --- Interactions + attendee links ---
    lines.append("-- Interactions")
    seen = {}
    for r in read("data/interactions.csv"):
        cust = r["customer"].strip()
        itype = r["type"].strip() or "meeting"
        date = r["date"].strip()
        title = r["title"].strip()
        notes = r["notes"].strip()
        iid = uid("int-" + slug(cust) + "-" + (date or "nd") + "-" + slug(title or notes), seen)
        date_expr = f"{q(date)}::timestamptz" if date else "now()"
        lines.append(
            f"INSERT INTO interactions (id, type, title, date, notes, customer_id, logged_by) VALUES "
            f"({q(iid)}, {q(itype)}, {q(title)}, {date_expr}, {q(notes)}, "
            f"(SELECT id FROM customers WHERE name = {q(cust)}), '') "
            f"ON CONFLICT (id) DO UPDATE SET type=EXCLUDED.type, title=EXCLUDED.title, "
            f"date=EXCLUDED.date, notes=EXCLUDED.notes, customer_id=EXCLUDED.customer_id;"
        )
        for nm in [x.strip() for x in r["mgt_attendees"].split(";") if x.strip()]:
            lines.append(
                f"INSERT INTO interaction_attendees_mgt (interaction_id, engineer_id) "
                f"SELECT {q(iid)}, id FROM engineers WHERE name = {q(nm)} LIMIT 1 "
                f"ON CONFLICT DO NOTHING;"
            )
        for nm in [x.strip() for x in r["external_attendees"].split(";") if x.strip()]:
            lines.append(
                f"INSERT INTO interaction_attendees_external (interaction_id, contact_id) "
                f"SELECT {q(iid)}, id FROM contacts WHERE name = {q(nm)} LIMIT 1 "
                f"ON CONFLICT DO NOTHING;"
            )
    lines.append("")

    # --- Team notes ---
    lines.append("-- Team notes")
    seen_tn = {}
    for r in read("data/team_notes.csv"):
        cust = r["customer"].strip()
        date = r["date"].strip()
        author = r["author"].strip()
        matched = r["author_matched"].strip() == "yes"
        context = r["context"].strip()
        body = r["notes"].strip()

        author_full = None
        if matched:
            author_full = author
        elif author:
            author_full = fmap.get(author.split()[0].lower())

        text = combine(context, body)
        if not author_full and author:
            text = f"{author}: {text}" if text else author  # preserve unmatched author label
        if not text:
            continue
        tnid = uid("tn-" + slug(cust) + "-" + (date or "nd") + "-" + slug(context or body), seen_tn)
        author_expr = (
            f"COALESCE((SELECT id FROM engineers WHERE name = {q(author_full)}), '')"
            if author_full else "''"
        )
        date_expr = f"{q(date)}::timestamptz" if date else "now()"
        lines.append(
            f"INSERT INTO team_notes (id, customer_id, author_id, text, created_at) VALUES "
            f"({q(tnid)}, (SELECT id FROM customers WHERE name = {q(cust)}), {author_expr}, "
            f"{q(text)}, {date_expr}) "
            f"ON CONFLICT (id) DO UPDATE SET author_id=EXCLUDED.author_id, text=EXCLUDED.text, "
            f"created_at=EXCLUDED.created_at;"
        )

    lines += ["", "COMMIT;"]
    with open(SQL_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Wrote {SQL_PATH}")


if __name__ == "__main__":
    main()
